// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0BvwQWQVvkbFOrT-fiLvH0tUaCvDd1BA',
    appId: '1:463933182416:web:da66ccab341dbd817769d5',
    messagingSenderId: '463933182416',
    projectId: 'innwa-production',
    authDomain: 'innwa-production.firebaseapp.com',
    storageBucket: 'innwa-production.appspot.com',
    measurementId: 'G-5MGC3KTGXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBor3lhwSDvMlxIFiylti93h_HeMuSVdX4',
    appId: '1:463933182416:android:d1304112b6c39c2a7769d5',
    messagingSenderId: '463933182416',
    projectId: 'innwa-production',
    storageBucket: 'innwa-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRMI7qaC4gOLD02nQS6V09lv056zKU2OM',
    appId: '1:463933182416:ios:ed6550d5c6769afd7769d5',
    messagingSenderId: '463933182416',
    projectId: 'innwa-production',
    storageBucket: 'innwa-production.appspot.com',
    iosBundleId: 'com.hanindustriesxneptune.zdotcom.innwa.innwaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRMI7qaC4gOLD02nQS6V09lv056zKU2OM',
    appId: '1:463933182416:ios:ed6550d5c6769afd7769d5',
    messagingSenderId: '463933182416',
    projectId: 'innwa-production',
    storageBucket: 'innwa-production.appspot.com',
    iosBundleId: 'com.hanindustriesxneptune.zdotcom.innwa.innwaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0BvwQWQVvkbFOrT-fiLvH0tUaCvDd1BA',
    appId: '1:463933182416:web:40452975dd1d6ee07769d5',
    messagingSenderId: '463933182416',
    projectId: 'innwa-production',
    authDomain: 'innwa-production.firebaseapp.com',
    storageBucket: 'innwa-production.appspot.com',
    measurementId: 'G-T04LW3575S',
  );
}
